### ISSUE TITLE
Date stopped in 04. April

### ISSUE THREAD

**Issue by estebaniglesias** [stevenliuyi/covid19#21] opened 2020-04-07 03:55 UTC
Hello, do you have any idea why the date has stopped in 04 April. I have deployed the map in my server and I have the same error.
Thanks!

**Comment by stevenliuyi** [comment] 2020-04-07 11:42
Hi! I'm not able to reproduce the issue. If you check the data file (`build/data/all_minified.json`), are you able to see the data after April 4?

**Comment by estebaniglesias** [comment] 2020-04-07 13:04
Hello, I have more information.
Here in Chile, me and also some friends, we see that the date under "Global", and the summary numbers are in the 4 april.
![Screenshot 2020-04-07 10 00 17](https://user-images.githubusercontent.com/2274485/78672232-60173e00-78ae-11ea-9237-38b36bb90d4f.png)

But if I enter with the Tor Browser, it shows (data and date) for the 7 april :O :O :O
![Screenshot 2020-04-07 10 00 21](https://user-images.githubusercontent.com/2274485/78672387-8e951900-78ae-11ea-9643-030461d96e22.png)

It happened that in Chile we moved into winter time the 04 of april. Do you think is has to bee with that?

**Comment by estebaniglesias** [comment] 2020-04-07 13:05
So somehow, the dashboard shows me the information for "my date," (which it thinks is still 04 april)...

**Comment by rafaelsabino** [comment] 2020-04-07 16:29
Good afternoon I don't believe this is the problem. When I go to the data folders I notice that the files have not been updated. It is as if even redoing the build he does not update. Very strange. I really wanted it to work. I wanted to show this excellent graphic to everyone in my city.

**Comment by estebaniglesias** [comment] 2020-04-07 16:38
What day do you see when you enter to https://covid19.health/ ?

**Comment by estebaniglesias** [comment] 2020-04-07 17:04
> Hi! I'm not able to reproduce the issue. If you check the data file (`build/data/all_minified.json`), are you able to see the data after April 4?

Yes and no... Because I am able to see updated data, but wrongly. For instance, for 05 april ad 06 april it does repeat the data of 03 april. For all countries.

![Screenshot 2020-04-07 13 03 07](https://user-images.githubusercontent.com/2274485/78698424-51418300-78d0-11ea-8bc1-4c28a1030f62.png)
![Screenshot 2020-04-07 13 03 18](https://user-images.githubusercontent.com/2274485/78698432-530b4680-78d0-11ea-945a-9918abfef4c3.png)
![Screenshot 2020-04-07 13 03 26](https://user-images.githubusercontent.com/2274485/78698435-543c7380-78d0-11ea-8687-e7997e345631.png)

**Comment by stevenliuyi** [comment] 2020-04-07 18:14
Hi, I am closing this issue so that we can discuss everything in one place (#23).

**Closed** 2020-04-07 18:14 UTC
