### ISSUE TITLE
"Configure Plots" leads to blank page

### ISSUE THREAD

**Issue by bubiman** [stevenliuyi/covid19#25] opened 2020-04-08 21:22 UTC
When clicking on the "Configure Plots" button (I like the log graph) I end up on an empty/blank page.
I tried this with Firefox and Chrome. 
I think this was working 2 days ago.

![configureplots](https://user-images.githubusercontent.com/6061436/78834961-a9bb7200-79ef-11ea-802a-47c1899bae79.png)

**Comment by stevenliuyi** [comment] 2020-04-11 06:21
Sorry that I am not able to reproduce this issue. It works fine for me. Do you still see blank page now?

**Comment by bubiman** [comment] 2020-04-12 10:12
I am sorry but it is still not working for me.
I tried it with my work laptop (chrome and firefox) and it is not working there either.

Just a blank/gray-ish page

**Comment by pmike1980** [comment] 2020-04-12 10:49
Hello,
I'm facing the same error on Google Chrome and Mozilla Firefox (latest versions).

Development console shows following errors:
`
Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ec (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at Object.enqueueSetState (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at t.O.setState (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at a.handleTempDateChange (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at value (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at _i (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at Xa (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at ju (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at bc (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at pc (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
fu @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
n.callback @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
Oi @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
gi @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
gc @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
t.unstable_runWithPriority @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
Vo @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
yc @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
ic @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
(anonymous) @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
t.unstable_runWithPriority @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
Vo @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
$o @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
Xo @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
ue @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
Sn @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
`
and
`
Uncaught Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ec (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at Object.enqueueSetState (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at t.O.setState (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at a.handleTempDateChange (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at value (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at _i (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at Xa (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at ju (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at bc (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
    at pc (39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1)
ec @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
enqueueSetState @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
O.setState @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
a.handleTempDateChange @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
value @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
_i @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
Xa @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
ju @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
bc @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
pc @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
ic @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
(anonymous) @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
t.unstable_runWithPriority @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
Vo @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
$o @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
Xo @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
ue @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
Sn @ 39c420264bae01bf58ed3aa9209eca9bcfc216ff.js:1
`

**Comment by stevenliuyi** [comment] 2020-04-12 21:25
@bubiman @pmike1980 Hi! I'm still not able to reproduce the error. One possibility is that the error is some how related to time zone (like #23). So maybe you could let me know what are the time zones of your operating systems, and then I can take a look at it to see if that's indeed the case.

**Comment by bubiman** [comment] 2020-04-13 07:35
I am living in germany so my time zone is UTC+1
![zeitzone](https://user-images.githubusercontent.com/6061436/79101967-0a3d0d00-7d6a-11ea-8fca-bf69a9a15e58.png)

**Comment by stevenliuyi** [comment] 2020-04-13 08:53
@bubiman @pmike1980 Hi, the issue should be fixed by now.

**Comment by bubiman** [comment] 2020-04-13 09:54
Yes it is ... thank you very much

**Closed** 2020-04-13 11:42 UTC
